# Generated by Django 3.2.4 on 2021-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_appointment_diagnosebill_diagnoseslip_medsbill_medsslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
