# Generated by Django 3.2.4 on 2021-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meds',
            old_name='price',
            new_name='b_price',
        ),
        migrations.AddField(
            model_name='meds',
            name='s_price',
            field=models.IntegerField(default=0),
        ),
    ]
