# Generated by Django 3.2.4 on 2021-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, choices=[('Ghaziabad', 'Ghaziabad'), ('New_Delhi', 'New Delhi'), ('Gurgaon', 'Gurgaon'), ('Sahaibabad', 'Sahaibabad')], max_length=100, null=True),
        ),
    ]
